#VictorOps Org Key
voOrganizationKey: ""

#VictorOps Routing Key
voRoutingKey: ""

#scheme used (http/https)
protocol: "https"

#VictorOps host
voAlertHost: "alert.victorops.com"

#VictorOps url path
voAlertUrlPath: "/integrations/generic/20131114/alert"

#http timeouts
connectTimeout: 10000
socketTimeout: 10000

#show appdynamics details in VO alert
showDetails: false



